name: Wine x86-64 Build Container

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:

jobs:
  archlinux:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README wine latest update date & Install depends
        run: |
          TZ=Asia/Shanghai

          # 下载 README 中的 Archlinux Rootfs
          wget -O archlinux-latest.tar.xz https://github.com/as14725836/BCC/releases/download/archlinux-latest/archlinux-latest.tar.xz
          sudo tar -xf archlinux-latest.tar.xz -C /tmp

          DATE_STR=$(TZ=$TZ date '+%Y-%m-%d %H:%M:%S %Z')
          sed -i "s/^- Wine x86-64 BCC Latest Update:.*/- Wine x86-64 BCC Latest Update: ${DATE_STR}/" README.md
          sudo chmod 777 Wine_x86-64-bcc.sh
          sudo cp -r Wine_x86-64-bcc.sh /tmp/archlinux/bin/
          sudo cp mount.sh /tmp/

          cd /tmp
          bash mount.sh mount archlinux
          sudo chroot archlinux /bin/Wine_x86-64-bcc.sh
          cd /tmp
          bash mount.sh unmount archlinux

      - name: Package
        run: |
          cd /tmp
          sudo tar -I 'xz -T$(nproc)' -cvf wine-bcc.tar.xz archlinux

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Wine x86-64 BCC
          draft: false
          prerelease: false
          tag_name: wine-bcc-latest
          body: |
            Wine x86-64 BCC rootfs
          files: /tmp/wine-bcc.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit README wine latest update date
        if: success()
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: update Wine x86-64 BCC latest date"
            git push
          fi
          
